FROM ghcr.io/yannh/kubeconform:latest-alpine
RUN apk add curl \ 
            openssl \
            bash
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh


