
.secrets_scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - gitleaks git ${TRACE+--log-level debug} $gitleaks_rule_opts --log-opts "$log_opts" --report-path gitleaks.json .
    - cat gitleaks.json
  allow_failure: true
  artifacts:
      name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
      when: always
      paths:
        - gitleaks.*