FROM node:20-alpine

RUN apk add --no-cache git
RUN npm install -g \
    semantic-release \
    @semantic-release/gitlab \
    @semantic-release/git \
    @semantic-release/exec \
    @semantic-release/commit-analyzer \
    @semantic-release/release-notes-generator \
    conventional-changelog-conventionalcommits
    